### ISSUE TITLE
How can GPU be used while training goes on?

### ISSUE THREAD

**Issue by hakanbogan** [MahmoudWahdan/dialog-nlu#17]
Hello there,

I realized while I train a joint transformer model, GPU is not used. How can I make it an active?

**Comment by MahmoudWahdan** [comment]
Hello @redrussianarmy 
If you have GPU on your device and installed tensorflow latest (version 2.3.0) and you are sure your GPU is compatible with tensorflow (please [see](https://www.tensorflow.org/install/gpu#software_requirements) ), then tensorflow runs on GPU if it's available by default.
If you are sure everything is installed correctly, you can do a quick test
```python
tf.test.is_gpu_available(
    cuda_only=False, min_cuda_compute_capability=None
)
``` 
It should return ```True``` otherwise there is a problem; may be your tensorflow installation didn't went well.
You can try uninstalling tensorflow and install it again.
```pip uninstall tensorflow```
```pip install tensorflow```

Please, let me know if works for you.

**Comment by hakanbogan** [comment]
Hello @MahmoudWahdan  
I tried to perform the test that you gave. It returned `True`. Finally, I found the solution:
Installed tensorflow version is 2.3.0. However, Cuda version was 10.0, cuDNN was 7.6.5. I have installed Cuda 10.1 and the training has worked on GPU. 

Thank you anyway.
